services:
  - type: web
    name: talentia-backend
    runtime: node
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: url_db
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: IA_SERVICE_URL
        sync: false
